(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({"J:\\xampp\\htdocs\\Trolist\\js\\TrolistWorker.js":[function(require,module,exports){
// Generated by CoffeeScript 1.8.0
(function() {
  var api, getLatestActions, getUpdateActions;

  api = require("./Utilites/trelloAPI");

  self.Trello = {};

  getLatestActions = function(onSuccess) {
    var API, postParams;
    if (onSuccess == null) {
      onSuccess = function() {};
    }
    postParams = {
      filter: "all",
      fields: "all",
      limit: 10
    };
    if (self.lastDate != null) {
      postParams.since = self.lastDate;
    }
    API = new api("/boards/" + self.boardId + "/actions", postParams);
    return API.run("GET", (function(_this) {
      return function(actionsData) {
        if (actionsData.length !== 0) {
          self.lastDate = actionsData[0].date;
        }
        return onSuccess(actionsData);
      };
    })(this));
  };

  getUpdateActions = function() {
    return getLatestActions(function(latestActions) {
      if (latestActions.length !== 0) {
        self.postMessage(latestActions);
      }
      return setTimeout((function() {
        return getUpdateActions();
      }), 100);
    });
  };

  self.addEventListener('message', function(e) {
    switch (e.data.cmd) {
      case "start":
        Trello.token = function() {
          return e.data.token;
        };
        Trello.key = function() {
          return e.data.key;
        };
        self.boardId = e.data.boardId;
        return getLatestActions(function() {
          return getUpdateActions();
        });
    }
  }, false);

}).call(this);

},{"./Utilites/trelloAPI":"J:\\xampp\\htdocs\\Trolist\\js\\Utilites\\trelloAPI.js"}],"J:\\xampp\\htdocs\\Trolist\\js\\Utilites\\trelloAPI.js":[function(require,module,exports){
// Generated by CoffeeScript 1.8.0
(function() {
  var trelloAPI;

  module.exports = trelloAPI = (function() {
    function trelloAPI(url, params) {
      var key, value;
      this.apiURL = "https://api.trello.com/1" + url + "?";
      for (key in params) {
        value = params[key];
        this.apiURL += "" + key + "=" + value + "&";
      }
      this.apiURL += "key=" + (Trello.key()) + "&token=" + (Trello.token());
      this;
    }

    trelloAPI.prototype.run = function(method, onSuccess) {
      var request;
      request = new XMLHttpRequest();
      request.open(method, this.apiURL, true);
      request.onload = (function(_this) {
        return function() {
          if (request.status >= 200 && request.status < 400) {
            return onSuccess(JSON.parse(request.responseText));
          } else {
            return console.error("Something's goes wrong! Error " + request.status, request.responseText);
          }
        };
      })(this);
      request.onerror = (function(_this) {
        return function() {
          return console.error("Something's goes wrong! API Error!");
        };
      })(this);
      return request.send(null);
    };

    return trelloAPI;

  })();

}).call(this);

},{}]},{},["J:\\xampp\\htdocs\\Trolist\\js\\TrolistWorker.js"]);
