// Generated by CoffeeScript 1.8.0
(function() {
  var Board, Trolist, api;

  api = require("./Utilites/trelloAPI");

  Board = require("./Objects/Board");

  Trolist = (function() {
    function Trolist() {}

    Trolist.prototype.init = function(data, startApp) {
      this.GLOBAL_BOARD = null;
      if (typeof data !== "object") {
        data = {
          appName: data,
          boardId: null,
          workerFile: null
        };
      }
      this.workerFile = data.workerFile;
      return Trello.authorize({
        name: data.appName,
        scope: {
          read: true,
          write: true,
          account: true
        },
        expiration: "never",
        success: (function(_this) {
          return function() {
            _this.key = Trello.key();
            _this.token = Trello.token();
            if (data.boardId === null) {
              return startApp(_this);
            } else {
              return _this.loadBoard(data.boardId, startApp);
            }
          };
        })(this),
        error: (function(_this) {
          return function(e) {
            return console.error("We have some problems to login");
          };
        })(this)
      });
    };

    Trolist.prototype.loadBoard = function(boardId, onSuccess) {
      var API;
      API = new api("/boards/" + boardId, {
        lists: "open",
        members: "all",
        member_fields: "all",
        list_fields: "all",
        fields: "name",
        labels: "all",
        label_fields: "all",
        cards: "open",
        card_fields: "all"
      });
      API.run("GET", (function(_this) {
        return function(boardData) {
          var worker;
          if (typeof Worker !== "undefined") {
            worker = new Worker(_this.workerFile);
            worker.postMessage({
              cmd: "start",
              token: Trello.token(),
              key: Trello.key(),
              boardId: boardData.id
            });
            worker.addEventListener("message", function(e) {
              return console.log(e.data);
            });
          } else {
            console.error("Error: Web Workers isnt supported in this browser!");
          }
          return _this.GLOBAL_BOARD = new Board(boardData, function(board) {
            return onSuccess(board);
          });
        };
      })(this));
      return this;
    };

    return Trolist;

  })();

  window.Trolist = new Trolist();

}).call(this);
