// Generated by CoffeeScript 1.8.0
(function() {
  var Label;

  module.exports = Label = (function() {
    function Label(labelData) {
      this.id = labelData.id;
      this.name = labelData.name;
      this.uses = labelData.uses;
      this.color = labelData.color;
    }

    return Label;

  })();

}).call(this);
