// Generated by CoffeeScript 1.8.0
(function() {
  var Member;

  module.exports = Member = (function() {
    function Member(memberData) {
      this.id = memberData.id;
      this.name = memberData.fullName;
      this.type = memberData.memberType;
      this.url = memberData.url;
      this.status = memberData.status;
      this.bio = memberData.bio;
      this.username = memberData.username;
      this.trelloObj = memberData;
      this.isAdmin = function() {
        return this.type === "admin";
      };
    }

    return Member;

  })();

}).call(this);
